services:
  app:
    # build:
    #     context: ..
    #     dockerfile: infra/build/Dockerfile
    image: bitcoinheist-app:latest
    command: flask --app src.app.main_api run --host 0.0.0.0 --port 5001
    depends_on:
      mlflow:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      airflow:
        condition: service_healthy
      pushgateway:
        condition: service_healthy
      grafana:
        condition: service_healthy
    ports:
      - "5001:5001"
    restart: "always"
    healthcheck:
      test: apt-get update -y && apt-get install -y curl && curl --fail http://localhost:8080 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - bitcoin-heist-data:/bitcoinheist-app/data
      - bitcoin-heist-models:/bitcoinheist-app/models
      - bitcoin-heist-telemetry:/bitcoinheist-app/telemetry

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.3.0rc0
    command: mlflow server --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: >
        apt-get update -y &&
        apt-get install -y curl &&
        curl --fail http://localhost:8080 || exit 1
      interval: 5s
      retries: 3
    volumes:
      - mlflow-data:/mlflow

  airflow:
    image: apache/airflow:3.1.0-python3.10
    command: airflow standalone
    environment:
      - _AIRFLOW_DB_MIGRATE=true
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=true
    ports:
      - "4242:8080"
    volumes:
      - ./airflow/dags/:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget http://localhost:8080/api/v2/monitor/health -o /dev/null || exit 1
      retries: 3
      interval: 5s
  
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./telemetry/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: wget http://localhost:9090/metrics -S -O - || exit 1
      retries: 3
      interval: 5s
  
  pushgateway:
    image: prom/pushgateway:v1.11.1
    ports:
      - "9091:9091"
    healthcheck:
      test: wget http://localhost:9091/metrics -S -O - || exit 1
      retries: 3
      interval: 5s

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./telemetry/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/login"]
      interval: 10s
      timeout: 5s
      retries: 5

# note: I use explicit volume names to prevent Docker Compose from auto-prefixing with the project name with infra_*
# note: this ensures the same volumes are shared between docker-compose services and Airflow DockerOperator tasks.
volumes:
  bitcoin-heist-data:
    name: bitcoin-heist-data
  bitcoin-heist-models:
    name: bitcoin-heist-models
  bitcoin-heist-telemetry:
    name: bitcoin-heist-telemetry
  mlflow-data: