services:
  # init-parquet:
  #   image: bitcoinheist-app:latest
  #   command: python scripts/csv_to_parquet.py
  #   restart: "no"
  #   volumes:
  #     - bitcoin-heist-data:/bitcoinheist-app/data

  # training:
  #   image: bitcoinheist-app:latest
  #   command: python src/main_training.py --preprocess --feat-eng --training
  #   depends_on:
  #     init-parquet:
  #       condition: service_completed_successfully
  #     mlflow:
  #       condition: service_healthy
  #   restart: "no"
  #   volumes:
  #     - bitcoin-heist-data:/bitcoinheist-app/data
  #     - bitcoin-heist-models:/bitcoinheist-app/models
  #     - bitcoin-heist-telemetry:/bitcoinheist-app/telemetry

  app:
    image: bitcoinheist-app:latest
    command: flask --app src.main_api run --host 0.0.0.0 --port 5001
    depends_on:
      mlflow:
        condition: service_healthy
      # prometheus:
      #   condition: service_healthy
      # telemetry_job:
      #   condition: service_started
    ports:
      - "5001:5001"
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - bitcoin-heist-data:/bitcoinheist-app/data
      - bitcoin-heist-models:/bitcoinheist-app/models
      - bitcoin-heist-telemetry:/bitcoinheist-app/telemetry

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.3.0rc0
    command: mlflow server --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: >
        apt-get update -y &&
        apt-get install -y curl &&
        curl --fail http://localhost:8080 || exit 1
      interval: 5s
      retries: 3
    volumes:
      - mlflow-data:/mlflow

  airflow:
    image: apache/airflow:3.1.0-python3.10
    command: airflow standalone
    environment:
      - _AIRFLOW_DB_MIGRATE=true
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=true
    ports:
      - "4242:8080"
    volumes:
      - ./airflow/dags/:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget http://localhost:8080/api/v2/monitor/health -o /dev/null || exit 1
      retries: 3
      interval: 5s
  
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./telemetry/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: wget http://localhost:9090/metrics -S -O - || exit 1
      retries: 3
      interval: 5s

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  bitcoin-heist-data:
  bitcoin-heist-models:
  bitcoin-heist-telemetry:
  mlflow-data:

networks:
  default:
    name: infra_default