global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "bitcoinheist-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:5001"]
  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]

rule_files:
  - "alerts.yml"